### ISSUE TITLE
"Undefined property: User::$field_photo" error

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/borg#1]
I'm having this error in the logs. I realized when I tried to change the logo of the site and didn't show up.

**Comment by ghost** [comment]
From @domaingood in https://github.com/backdrop-contrib/borg/issues/3:
> Notice: Undefined property: User::$field_photo in borg_preprocess_node() (line 237 of /themes/borg/template.php).

**Comment by jenlampton** [comment]
Committed a fix for this.
