### ISSUE TITLE
Responsive header issues

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/borg#11]
This bug is visible on the API site when viewing on a screen size < 990px and > 768px.

![image](https://user-images.githubusercontent.com/2385329/69401763-99d01980-0cfe-11ea-84ee-56dabe23d31b.png)

The slogan doesn't wrap and sits on top of the absolutely positioned `system-user-menu` block.

Also, the `system-user-menu` block sits close to the bottom of the header and doesn't look nice anymore (since the font-size change I believe). Changing `top: -5px;` to `top: -14px` fixes this.

![image](https://user-images.githubusercontent.com/2385329/69401954-224eba00-0cff-11ea-92d8-b2694f26b54d.png)

**Comment by jenlampton** [comment]
> Changing top: -5px; to top: -14px fixes this.

Does this change work ok for the other sites too? If so, would you please create a PR? :)

**Comment by ghost** [comment]
> Does this change work ok for the other sites too?

Hard to tell, as each site uses a different version of Borg...

- Bcms.org: 1.x-1.1.14
- API: 1.x-1.1.12
- Forum: 1.x-1.1.13

**Comment by jenlampton** [comment]
Well need to test the new version of botlrg on each site with the change to
tell.

**Comment by ghost** [comment]
The only site this is an issue on is the API/Docs site, and there's a custom theme for that, so closing this issue in favour of this one (with a PR): https://github.com/backdrop-ops/docs.backdropcms.org/issues/119
