### ISSUE TITLE
Typo in alt text for Twitter icon.

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/borg#17]
The alt text for the Twitter icon in the top right corner of the Backdrop CMS home page has a typo. It should read "Follow us on Twitter" instead of "Follow os on Twitter".

**Comment by ghost** [comment]
@Radcliffe Made a PR here: https://github.com/backdrop-contrib/borg/pull/18

**Comment by ghost** [comment]
PR looks good. RTBC from me.
