### ISSUE TITLE
Grid format in Views throws an error

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/borg#2]
I tried to use the theme on a site that used the Grid format in Views, and when I looked at the Views page, it showed bunch of error messages, variants on these two:
Warning: Invalid argument supplied for foreach() in borg_preprocess_views_view_grid() (line 317 of /Applications/MAMP/htdocs/qdbackdrop/themes/borg/template.php).
....
Warning: Invalid argument supplied for foreach() in include() (line 25 of /Applications/MAMP/htdocs/qdbackdrop/themes/borg/templates/views-view-grid.tpl.php).

**Comment by jenlampton** [comment]
I think those overrides were put in before Views grids had CSS grid support. There's a checkbox in the view to use the legacy output, if you check that box the errors should go away.

I do still think we need to update this theme so this doesn't happen at all.

**Comment by jenlampton** [comment]
I've added a check for the deprecated table setting, and only applied these changes when that setting is active.

**Comment by jenlampton** [comment]
I've also added the more modern markup for CSS grid into the `views-view-grid` template, so that new views will be unaffected.
