### ISSUE TITLE
Fix Showcase page styling

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/borg#28]
In https://github.com/backdrop-ops/backdropcms.org/commit/041852b57485a0d6024b7392efff11435c2426f3 I added some CSS to fix the styling of the Showcase page, but I accidentally added it to the Borg theme in the B.org repo, as opposed to https://github.com/backdrop-contrib/borg

When the Borg theme in the B.org repo was updated, those changes were wiped and now the Showcase page shows in one-column rather than two.

This issue/PR is for adding the CSS back to the Borg theme, but in the right repo this time 😉

**Comment by ghost** [comment]
@jenlampton PR here: https://github.com/backdrop-contrib/borg/pull/29

If you're happy to merge, please also create a new release of borg then update B.org with it so we can fix this issue. Thanks!

**Comment by jenlampton** [comment]
@BWPanda Merged, thank you! We're going to have a new release of borg shortly anyway. If you want to update b.org with the patch from the PR before then, go ahead, but please document it in the PATCHES.txt file :)
