### ISSUE TITLE
Add lost password link from b.org to borg theme.

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/borg#32]
The Borg theme removes the tabs from the login page (and other `user/*` pages: https://github.com/backdrop-contrib/borg/blob/578efe165881b56a18369e03ecb8b6b1c8d93328/template.php#L186 This has the effect of hiding the link to reset your password.

On BackdropCMS.org this is fixed by adding a 'Forgot password?' link next to the Login button, however this happens in a custom module (https://github.com/backdrop-ops/backdropcms.org/blob/af96ca5a1df50ec30ac54d51e1d30eb033931b9b/www/modules/custom/borg_cleanup/borg_cleanup.module#L33), so other sites that use Borg (like Docs) have the reset link removed from the tabs area, but it's not added back anywhere...

I think if Borg removes the tabs, it should also add the link back where necessary (i.e. the code from the b.org custom module should be moved to the Borg theme).

**Comment by jenlampton** [comment]
> I think if Borg removes the tabs, it should also add the link back where necessary (i.e. the code from the b.org custom module should be moved to the Borg theme

That's a great idea. Yes.

**Comment by jenlampton** [comment]
This commit has been aded and will be included in the next release.
