### ISSUE TITLE
Front page with new content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/borg#33]
FYI 

![borg-cards](https://user-images.githubusercontent.com/3144571/165420489-4b54d9fe-2ed1-4e51-8499-00c19ec7a1cb.png)

**Comment by jenlampton** [comment]
I would like to include support for this in version 1.2.1

**Comment by jenlampton** [comment]
<img width="1333" alt="Screenshot 2024-01-29 at 2 03 51 PM" src="https://github.com/backdrop-contrib/borg/assets/397895/084ae11b-cd37-42ba-bc8d-6dba9b839a89">
<img width="778" alt="Screenshot 2024-01-29 at 2 05 53 PM" src="https://github.com/backdrop-contrib/borg/assets/397895/6e08e164-0e28-43fb-a252-64ca6913b87a">
<img width="434" alt="Screenshot 2024-01-29 at 1 58 52 PM" src="https://github.com/backdrop-contrib/borg/assets/397895/bbebf826-802b-4ff8-99a5-09ff97b6e66e">
