### ISSUE TITLE
Make content wider on wide screens

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/borg#40]
When viewing source code currently (e.g. on the docs/api site), some lines are breaking in a messy way:
![CleanShot 2024-03-20 at 09 12 38@2x](https://github.com/backdrop-contrib/borg/assets/871421/56bb1d8d-9e85-4461-a562-10e1dc3f2677)

If we allowed the content to go wider on wider screens, it would look much nicer:
![CleanShot 2024-03-20 at 09 11 38@2x](https://github.com/backdrop-contrib/borg/assets/871421/0984eb72-183e-4b03-8867-bd9dd27a850c)

**Comment by jenlampton** [comment]
This width is coming from the bootstrap grid in core. I think it would be nice to make the page wider for this specific use-case, but I think that belongs on the API site, only, and perhaps specifically for the API pages? 

We'll need to do a lot of testing on all the different types of pages on all the sites if we want to increase the max page-width globally. I'm not opposed to it but I would like to fix this specific problem first, and quickly :)

**Comment by jenlampton** [comment]
This is fixed for the docs site source code use case: https://docs.backdropcms.org/api/backdrop/modules%21examples%21examples.module/1
