### ISSUE TITLE
Add a 'code' Inline Style to CKeditor settings.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/borg#8]
Please include an Inline Style in the CKeditor settings so that a `code` style can be applied to words as a `span`.

**Comment by Graham-72** [comment]
This uses the existing 'monospace' style already in the CKeditor settings.

**Comment by jenlampton** [comment]
@Graham-72 Would you please create a PR from the commit on your branch? Did you do that already? I may have missed it...

**Comment by Graham-72** [comment]
@jenlampton it should now be here https://github.com/backdrop-contrib/borg/pull/12

**Comment by jenlampton** [comment]
Thanks for the PR @Graham-72  sorry it took me so long to find it!
